version: "3.9"

services:
  head:
    build: .
    volumes:
      - .:/app
    shm_size: "2gb"
    command: sh -c "ray start --head --port=6379 --dashboard-host=0.0.0.0 && flask run --host=0.0.0.0"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    hostname: head
    ports:
      - "5000:5000"
      - "8265:8265"

  worker_1:
    build: .
    volumes:
      - .:/app
    shm_size: "2gb"
    command: sh -c "ray start --address='172.16.238.10:6379' --redis-password='5241590000000000' && tail -f /dev/null"
    networks:
      app_net:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11
    hostname: worker_1
    depends_on:
      - head

  worker_2:
    build: .
    volumes:
      - .:/app
    shm_size: "2gb"
    command: sh -c "ray start --address='172.16.238.10:6379' --redis-password='5241590000000000' && tail -f /dev/null"
    networks:
      app_net:
        ipv4_address: 172.16.238.12
        ipv6_address: 2001:3984:3989::12
    hostname: worker_2
    depends_on:
      - head

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
